import { daysAgo } from "../_shared";
import type { ProjectContext } from "./types";

export const mockContexts: ProjectContext[] = [
  {
    id: "ctx_launch",
    projectId: "prj_launch",
    product: "Produto X",
    brand: "Acme",
    productDescription: "Plataforma de automação de marketing focada em times de growth.",
    targetAudience: "Growth managers e times de marketing B2B",
    platform: "LinkedIn, Blog, Email",
    goal: "Gerar leads qualificados para o lançamento",
    language: "pt-BR",
    toneOfVoice: "Profissional, confiante e inspirador",
    avatar: "Ana, 32, Head of Growth em SaaS B2B",
    offer: "Trial gratuito de 14 dias com onboarding assistido",
    defaultCTA: "Comece seu trial gratuito",
    country: "Brasil",
    restrictions: "Não usar promessas absolutas ou linguagem sensacionalista.",
    additionalInformation: "Campanha de lançamento com duração de 6 semanas.",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: "ctx_tiktok",
    projectId: "prj_tiktok",
    product: "TikTok Shop UGC",
    brand: "Creators Hub",
    productDescription: "Roteiros curtos para creators promoverem produtos no TikTok Shop.",
    targetAudience: "Creators com 10k–200k seguidores",
    platform: "TikTok",
    goal: "Aumentar conversão de UGC em vendas diretas",
    language: "pt-BR",
    toneOfVoice: "Casual, direto e autêntico",
    avatar: "Bia, 24, criadora de conteúdo lifestyle",
    offer: "Comissão por venda + brindes exclusivos",
    defaultCTA: "Compre pelo link na bio",
    country: "Brasil",
    restrictions: "Evitar termos proibidos pela política do TikTok Shop.",
    additionalInformation: "Vídeos entre 15s e 45s. Hook forte nos 3s iniciais.",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
  },
  {
    id: "ctx_veo",
    projectId: "prj_veo",
    product: "Veo 3 Cinematic",
    brand: "Studio Nova",
    productDescription: "Prompts JSON cinematográficos para o modelo Veo 3.",
    targetAudience: "Diretores criativos e produtoras audiovisuais",
    platform: "Veo 3, Runway",
    goal: "Padronizar geração de vídeos cinematográficos de alta qualidade",
    language: "en-US",
    toneOfVoice: "Cinematográfico, descritivo e técnico",
    avatar: "Carlos, 38, diretor de arte publicitário",
    offer: "Biblioteca de estilos pré-configurados",
    defaultCTA: "Explore os presets",
    country: "Global",
    restrictions: "Não usar personagens reais ou marcas registradas.",
    additionalInformation: "Sempre incluir descrição de câmera, iluminação e lente.",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(4),
  },
  {
    id: "ctx_blog",
    projectId: "prj_blog",
    product: "Blog SEO PT-BR",
    brand: "Conteúdo Pro",
    productDescription: "Artigos otimizados para SEO em português.",
    targetAudience: "Leitores buscando soluções práticas em marketing digital",
    platform: "Blog / Google Search",
    goal: "Rankear no top 3 para palavras-chave estratégicas",
    language: "pt-BR",
    toneOfVoice: "Didático, informativo e amigável",
    avatar: "Diego, 29, empreendedor digital iniciante",
    offer: "Newsletter semanal gratuita",
    defaultCTA: "Assine a newsletter",
    country: "Brasil",
    restrictions: "Sem plágio. Evitar keyword stuffing.",
    additionalInformation: "Estrutura E-E-A-T com FAQs e schema.org.",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: "ctx_saas",
    projectId: "prj_saas",
    product: "SaaS Onboarding",
    brand: "FlowApp",
    productDescription: "Fluxos guiados de ativação para novos usuários SaaS.",
    targetAudience: "Novos usuários no primeiro login",
    platform: "App Web, Email",
    goal: "Elevar ativação para acima de 60% em 7 dias",
    language: "en-US",
    toneOfVoice: "Encorajador, claro e conciso",
    avatar: "Erika, 27, gerente de operações em startup",
    offer: "Consultoria de setup gratuita no plano anual",
    defaultCTA: "Complete seu setup",
    country: "Global",
    restrictions: "Não usar jargões técnicos sem contexto.",
    additionalInformation: "Sequência de 5 emails + 3 tooltips in-app.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(6),
  },
  {
    id: "ctx_chars",
    projectId: "prj_chars",
    product: "Personagens IA",
    brand: "Casting AI",
    productDescription: "Biblioteca de avatares reutilizáveis para geração de conteúdo.",
    targetAudience: "Times criativos e estúdios",
    platform: "Midjourney, Veo 3",
    goal: "Criar consistência visual entre projetos",
    language: "pt-BR",
    toneOfVoice: "Descritivo, coeso e narrativo",
    avatar: "Fernanda, 34, art director",
    offer: "Templates de personagens prontos",
    defaultCTA: "Explore o casting",
    country: "Brasil",
    restrictions: "Não gerar semelhança com pessoas reais.",
    additionalInformation: "Cada personagem tem seed, LORA e prompt base.",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(7),
  },
  {
    id: "ctx_arch",
    projectId: "prj_arch",
    product: "Legacy 2024",
    brand: "Arquivo",
    productDescription: "Projetos históricos arquivados em 2024.",
    targetAudience: "Uso interno",
    platform: "Interno",
    goal: "Manter histórico para consulta",
    language: "pt-BR",
    toneOfVoice: "Neutro",
    avatar: "—",
    offer: "—",
    defaultCTA: "—",
    country: "Brasil",
    restrictions: "Somente leitura.",
    additionalInformation: "Não usar em novas campanhas.",
    createdAt: daysAgo(200),
    updatedAt: daysAgo(90),
  },
  {
    id: "ctx_dev",
    projectId: "prj_dev",
    product: "DevRel Content",
    brand: "DevHub",
    productDescription: "Documentação e tutoriais para desenvolvedores.",
    targetAudience: "Desenvolvedores full-stack",
    platform: "Docs, GitHub, Blog",
    goal: "Elevar adoção da API e reduzir tickets",
    language: "en-US",
    toneOfVoice: "Técnico, direto e prático",
    avatar: "Gustavo, 31, senior developer",
    offer: "Créditos gratuitos para novos devs",
    defaultCTA: "Read the docs",
    country: "Global",
    restrictions: "Sempre incluir exemplos de código testáveis.",
    additionalInformation: "Manter tom consistente com a documentação oficial.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
];