/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Veo3RouteImport } from './routes/veo3'
import { Route as TiktokShopRouteImport } from './routes/tiktok-shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ImageStudioRouteImport } from './routes/image-studio'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsNewRouteImport } from './routes/prompts.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const Veo3Route = Veo3RouteImport.update({
  id: '/veo3',
  path: '/veo3',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokShopRoute = TiktokShopRouteImport.update({
  id: '/tiktok-shop',
  path: '/tiktok-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageStudioRoute = ImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsNewRoute = PromptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PromptsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/characters': typeof CharactersRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/image-studio': typeof ImageStudioRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tiktok-shop': typeof TiktokShopRoute
  '/veo3': typeof Veo3Route
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/prompts/new': typeof PromptsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/characters': typeof CharactersRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/image-studio': typeof ImageStudioRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tiktok-shop': typeof TiktokShopRoute
  '/veo3': typeof Veo3Route
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/prompts/new': typeof PromptsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/characters': typeof CharactersRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/image-studio': typeof ImageStudioRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tiktok-shop': typeof TiktokShopRoute
  '/veo3': typeof Veo3Route
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/prompts/new': typeof PromptsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/characters'
    | '/favorites'
    | '/help'
    | '/image-studio'
    | '/library'
    | '/projects'
    | '/prompts'
    | '/settings'
    | '/tiktok-shop'
    | '/veo3'
    | '/projects/$projectId'
    | '/prompts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/characters'
    | '/favorites'
    | '/help'
    | '/image-studio'
    | '/library'
    | '/projects'
    | '/prompts'
    | '/settings'
    | '/tiktok-shop'
    | '/veo3'
    | '/projects/$projectId'
    | '/prompts/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/characters'
    | '/favorites'
    | '/help'
    | '/image-studio'
    | '/library'
    | '/projects'
    | '/prompts'
    | '/settings'
    | '/tiktok-shop'
    | '/veo3'
    | '/projects/$projectId'
    | '/prompts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CharactersRoute: typeof CharactersRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  ImageStudioRoute: typeof ImageStudioRoute
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromptsRoute: typeof PromptsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TiktokShopRoute: typeof TiktokShopRoute
  Veo3Route: typeof Veo3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veo3': {
      id: '/veo3'
      path: '/veo3'
      fullPath: '/veo3'
      preLoaderRoute: typeof Veo3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-shop': {
      id: '/tiktok-shop'
      path: '/tiktok-shop'
      fullPath: '/tiktok-shop'
      preLoaderRoute: typeof TiktokShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-studio': {
      id: '/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof ImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/new': {
      id: '/prompts/new'
      path: '/new'
      fullPath: '/prompts/new'
      preLoaderRoute: typeof PromptsNewRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface PromptsRouteChildren {
  PromptsNewRoute: typeof PromptsNewRoute
}

const PromptsRouteChildren: PromptsRouteChildren = {
  PromptsNewRoute: PromptsNewRoute,
}

const PromptsRouteWithChildren =
  PromptsRoute._addFileChildren(PromptsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CharactersRoute: CharactersRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  ImageStudioRoute: ImageStudioRoute,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromptsRoute: PromptsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TiktokShopRoute: TiktokShopRoute,
  Veo3Route: Veo3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
